### ISSUE TITLE
Could you share the easydict and the pickle files?

### ISSUE THREAD

**Issue by zzxzzx123** [huitailangyz/AFGAN#1]
Congratulation, an amazing work. I want to train the network by myself.  Could you share the easydict and the pickle files?  That's would be better if you can release your pretrained model.  Thanks.

**Comment by huitailangyz** [comment]
We have updated the code by adding a file named `split_dataset.py`. This file can be used to generate the pickle files. And the easydict is a library of python instead of a single file. Since the pretrained model is a little bit large. It is inconvenient to upload the pretrained model.

**Comment by zzxzzx123** [comment]
Could you share your AlexNet_epoch_99.pth file? I can't find it on the Internet. Thank you.

**Comment by huitailangyz** [comment]
We have uploaded the file to google drive, please follow the update in `README.md`. Thank you for your attention to our work.

**Comment by cookie-ke** [comment]
> Could you share your AlexNet_epoch_99.pth file? I can't find it on the Internet. Thank you.

Have you run this code successfully? I'd like to ask you some questions.
