### ISSUE TITLE
The data set 

### ISSUE THREAD

**Issue by cookie-ke** [huitailangyz/AFGAN#3]
Can you share the data set you use? The dataset you are using appears to have only 18 attributes, and the attribute values are represented as 0 and 1.

**Comment by huitailangyz** [comment]
The dataset used in our paper in the CelebA dataset. You can get access to it from [CelebA](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html). 
The dataset has 40 attributes about facial features. We select 18 from the 40 attributes, and the full list of the attributes we used you can find in Tab. 1 in [our paper](https://arxiv.org/abs/2012.01782).

**Comment by cookie-ke** [comment]
> The dataset used in our paper in the CelebA dataset. You can get access to it from [CelebA](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html).
> The dataset has 40 attributes about facial features. We select 18 from the 40 attributes, and the full list of the attributes we used you can find in Tab. 1 in [our paper](https://arxiv.org/abs/2012.01782).

Thank you very much! I've processed the data set, but I don't know if I've processed it accurately. The original size of the image of the data set is not 64*64. Is it feasible for me to change it to 64*64 directly through "resize"?
